### ISSUE TITLE
Fix all the things I brought up in a recent email

### ISSUE THREAD

**Issue by garrett** [devconfcz/devconfcz#36]
I've fixed almost all the things I brought up with the email. However, there are a few little items left. This is a tracking bug to not forget these few small items.
## 
### Checklist:
- [x] Wrong fonts. The correct font is Montserrat (not Overpass).
- [ ] Telegram and email icons are strangely huge and too close to each other as-is. The icons and color are out of place and do not fit the rest of the site.
- [ ] Top heading bar is pretty much invisible. It uses a light grey similar to most browsers. The bar should be more colorful and/or darker to be noticed if the navigation is going to be at the top. As is, it is camouflaged and blends in to most peoples' browsers.
- [x] Spacing is haphazardly all over the place.
- [x] Intro should be width-constrained (by em/ex units so it is relative to the font size) and an attempt should be made to make it break across lines a bit better. ("A free annual community conference for developers, admins, and users of Linux & JBoss")
- [x] The photo abruptly ends into white. It looks bad like this.
- [x] Font size is inconsistent, and a lot of it is way, way, way too small (lists, quotes, etc.).
- [x] "Brought to you by Red Hat" is shown multiple times, which is a little odd, especially since one of the graphics has text included on the image.
- [x] Icons next to text have no spacing between the icon and text. (Referring to the video links in the CfP section... the play icon should have margin-right: 0.5ex or a value between 0.5 and 1ex.)
- [x] Inline styles should NEVER, EVER be used. Everything should be in a stylesheet.
- [x] There's an improper document structure. The H1s everywhere should probably be H2s or lower (depending on content and context). You really should only have one H1 on a page.
  https://w3c.github.io/html/sections.html#the-h1-h2-h3-h4-h5-and-h6-elements
  http://html5doctor.com/outlines/
- [ ] When scrolling down and the page isn't super-wide, the navigation becomes overlapped with the DevConf logo.
- [x] The "Last time..." header could imply that this is the last time. You should change this to "Previously at DevConf.cz..." or "What people say about DevConf" or something similar.
- [x] Line-height is inconsistent, and in many places (such as quotes) too small.
- [ ] What's up with the social icons on the top-right? Each one links to DevConf somewhere except the red blob thing... and that website is confusing if someone lands on it (it looks like a placeholder site, as it isn't obvious one should scroll down — and even when scrolling, things bounce all over the place... but that's a different issue). The Winter of Code site should be linked differently... probably with some text at the bottom, explaining what it is.
- [x] What's up with the random italics?
- [x] Why are headings (which shouldn't be H1 — see #11) wrapped in a div? Headings can be styled with CSS just fine. Why is that div named with a presentation class instead of named on function? You shouldn't name things based on how they look, but what they do.
- [x] It's not obvious that you should scroll down on the page and/or click on the navigation at the top (as it's nearly invisible — see #2). Therefore, the page looks like a placeholder with no additional information.

**Comment by frantisekz** [comment]
@garrett Thanks for summing this up.
I wanted to ask about "Wrong fonts. The correct font is Montserrat (not Overpass)." - When/Where was agreed to use Montserrat font? This is probably not that important atm since there are bugs present in rendering Overpass on some configurations.

**Comment by garrett** [comment]
@frantisekz: Quick summary of emails from a while back: There was a discussion about the logo. The logo itself uses a modified version of Montserrat. Overpass (another opinionated title font) clashes with the typography used in the logo, so it's basically incompatible and shouldn't be paired with the logo.

(Overpass is a nice font, but it is often overused — it should be used for an official Red Hat corporate feel, not for community projects and events — and it should never really be used for body text, by-the-way.)

**Comment by kejbaly2** [comment]
I agree with this summary. Thanks for hacking the fixes. 

The remaining items... Fix them however you think is most pleasing to you.
