### ISSUE TITLE
Move to Jekyll?

### ISSUE THREAD

**Issue by garrett** [devconfcz/devconfcz#48]
The site is getting more and more complex. It's no longer a single page site. As a result, the pages are all inconsistent.

In addition, there have been a bunch of HTML issues lately that have been showing up as a result of manual HTML editing.

I suggest we move things to a static site generator. 

As Jekyll is natively handled by GitHub, I'm going to say it makes the most sense. However, I don't have experience with Jekyll. I looked into it today for a bit, but we all need to agree on this before moving forward.

---

Does anyone on the team have experience with Jekyll? I have experience with Middleman and converting documents to Markdown — but with not Jekyll itself.

**Comment by kejbaly2** [comment]
I was thinking the same thing. I was going to loom into jekyll. I'll take a
pass at it this week.

**Comment by garrett** [comment]
I have it ported to Jekyll in a branch. I need to finish it, but hopefully will get it to a state to share it tomorrow (at least in some form).

**Comment by garrett** [comment]
This is taking longer than I had expected. I'm still working on it, but as the goal is to make it so GitHub can auto-generate the site with Jekyll, it limits what is possible... so I'm coming up with some workarounds to simplify everything still, but it isn't as straightforward as I had thought.

(I had it all working fine until I tried getting GitHub to display it... then realized that GitHub doesn't support most Jekyll modules _and_ it builds the site in "safe mode"... so I had to read up a lot and try a lot of things... I still think it's possible, and I have something working here locally, so it will be time to test it on GitHub again soon.)

**Comment by garrett** [comment]
I have it up and running:
https://garrett.github.io/devconfcz-jekyll/

It still needs a bit more work, even if it looks about right already. But I have this auto-building automatically via GitHub Pages through Jekyll already, with some template/content separation as well as including some upstream modules (via Bower now, so it's included in the git repo, but can be easily updated and managed, and there's no fuss with git modules) — so this is a great start.
