### ISSUE TITLE
DevConf.cz Icon

### ISSUE THREAD

**Issue by kejbaly2** [devconfcz/devconfcz#53]
I think we might still need a standalone icon for DevConf.cz that can potentially be put on SWAG that clearly represents DevConf.cz without needing the full logo.

Current Icon is here: 

![image](https://cloud.githubusercontent.com/assets/3764092/18778909/0eaa3c70-8177-11e6-9ae4-4d5803595244.png)

Previous year's icon was:

![image](https://cloud.githubusercontent.com/assets/3764092/18778921/16f645ae-8177-11e6-8bfc-baed3509f532.png)

**Comment by kejbaly2** [comment]
SWAG with the icon

![image](https://cloud.githubusercontent.com/assets/3764092/18779082/af966564-8177-11e6-8cd4-ff18e21c3e83.png)

**Comment by kejbaly2** [comment]
More SWAG with icon ![2016_devconf_lanyard_1](https://cloud.githubusercontent.com/assets/3764092/18779140/e982f530-8177-11e6-9f93-0623033957cc.png)

**Comment by kejbaly2** [comment]
Just showing last year's SWAG to as a reminder of what the icon might be used on.

Or perhaps we just always use the full logo? hrm...

![image](https://cloud.githubusercontent.com/assets/3764092/18779185/2dc1b1f0-8178-11e6-8d25-79d882025062.png)

**Comment by kejbaly2** [comment]
Speaking of SWAG, ie, traditionally we alwasy have given all speakers a sweatshirt/pull over and plan to do the same this year, just with updated design so we need to decide on color scheme so we can get some samples from the vendor sooner than later... ideally within the next few weeks have some ideas ready.

**Comment by kejbaly2** [comment]
and last year, note, we had the devconf icon sewed onto the shirt and then some text and sponsor logos printed on the back.

![image](https://cloud.githubusercontent.com/assets/3764092/18781240/3fd44c28-8181-11e6-8eb0-c9f5c4a69a1e.png)

**Comment by garrett** [comment]
![Uploading devconfcz-icon-square.png…]()

Here's a possible square-based icon with logotext on top, inspired by the previous year's square one. What do you think?

**Comment by deekej** [comment]
Looks good, @garrett. Do you think you could just update the bottom of the square logo to have same shape as "crystal ball" in normal logo? I see that the bottom of this square logo is much more rounded than the normal logo... :)

Here's one more idea, to make the logo look closer to standard/normal DevConf logo:
Add an outer line of black, than have inner line of white (as of right now), than have the purple part in the middle... :)

**Comment by garrett** [comment]
One of the challenges with this graphic is that it will be displayed at smaller sizes. It shouldn't be too complex. Having additional strokes will probably make it a bit too complex. However, I guess if it's small enough, it could just add a bit more definition.

Here's a version that started with a black line around the globe, but inside the white line. I then softtened it up to make it not really black, but dark purple. Then I thought I might as well see what it looks like stylized a little more and added a radial gradient to make the globe look a little more sphere-like, as if it had an inner-light. Of course, I made sure to make that really subtle as to not take away from the rest of the graphic.

![devconfcz-icon-square-2](https://cloud.githubusercontent.com/assets/10246/20181105/351d5354-a75d-11e6-87cd-f0ca4ff21234.png)

I also tweaked the base a bit more too.

**Comment by garrett** [comment]
![devconfcz-icon-square-2-blackline](https://cloud.githubusercontent.com/assets/10246/20181195/7dc92b50-a75d-11e6-8f04-50f306de25d8.png)

Here's one with a solid black line that's a bit thicker. I also pulled the white line out a bit more too (to compensate for the thicker black line).

**Comment by deekej** [comment]
I find the last version most "natural" to look at... :)

**Comment by garrett** [comment]
@deekej: Great! We agree. I like it best too.

I guess I need to update the base on the logo to be more like this. (It's a subtle modification.)

**Comment by kejbaly2** [comment]
Looking good!

**Comment by jridky** [comment]
@garrett It looks really good. Please, can you create this icon even with transparent background (instead of black) for mobile app icon purposes?

**Comment by garrett** [comment]
A transparent background version probably needs a black outline instead of a white one.

Here's a quick mod to support that:

![devconfcz-icon-square-2-transparent](https://cloud.githubusercontent.com/assets/10246/20257837/8453da64-aa4c-11e6-9834-3164269eb62f.png)

(The text is still white, as it is still on a darker purple color.)

**Comment by garrett** [comment]
Added SVG for current versions to the repo in the above pull request (commit c7f7019868282f4bcbc2eaf33247fdc295f3fbd8)
