### ISSUE TITLE
DevConf Posters

### ISSUE THREAD

**Issue by kejbaly2** [devconfcz/devconfcz#54]
Need some CfP posters; A4 and ready for Digital Signage

What: DevConf.cz 2017 Call for Proposals (CfP)
When: Jan 27-29
Where: Brno, CZ

A free annual community conference for developers, admins, and users of Linux & JBoss
# DEFINEfuture

QR code (png/svg will be added to the repo)
Not sure which is better, direct to the CfP or rather to devconf.cz itself... prolly devconf.cz itself...

![devconfcz-qrcode](https://cloud.githubusercontent.com/assets/3764092/18780345/63faa89e-817d-11e6-91a0-b742de9e65fa.png)

**Comment by kejbaly2** [comment]
We could keep things simple and prolly just use some variant of the landing page as the poster... + the QR code

**Comment by kejbaly2** [comment]
I need posters... thoughts on this (or something like this...)?  Trying to reuse the existing theme as much as possible... 

[DevConf Poster - CfP.pdf](https://github.com/kejbaly2/devconfcz/files/502746/DevConf.Poster.-.CfP.pdf)

**Comment by kejbaly2** [comment]
CfP Poster I'm putting up in Brno office is here... 
[ore! (9).pdf](https://github.com/kejbaly2/devconfcz/files/505764/ore.9.pdf)

**Comment by frantisekz** [comment]
@kejbaly2 I am not sure if it's ideal to use submit a talk as a button on poster? I'd find better having simple text "Submit a talk" instead of button. Just my opinion :)

**Comment by kejbaly2** [comment]
I don't disagree... but i need posters yesterday so...  doing what I can with what I have.
